=begin

Gem é um pacote que oferece funcionalidades a fim de resolver
uma necessidade específica de um programa Ruby.
Pense como o conceitode biblioteca em outras linguagens de
programação.

=end


source 'https://rubygems.org'

gem 'os'
